//
// Created by Brandon on 1/17/26.
//

#ifndef RGBLIB_IRBUTTONTYPE_H
#define RGBLIB_IRBUTTONTYPE_H

enum class IRButtonType {
  ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO,
  STAR, POUND, UP, DOWN, LEFT, RIGHT, OK, UNKNOWN
};

#endif //RGBLIB_IRBUTTONTYPE_H
